### ISSUE TITLE
Add a new valuable feature 

### ISSUE THREAD

**Issue by realsahilsaini** [realsahilsaini/IEEE-Task#4]
Add a new valuable feature to this registration site.

For example: Chat on the WhatsApp button, toggle for dark/light mode, maps, etc.

**Comment by aryaupadhyay24** [comment]
Hello I'm Arya Upadhyay, I want to work on this issue

**Comment by realsahilsaini** [comment]
> Hello I'm Arya Upadhyay, I want to work on this issue

Sure, go ahead!
